### ISSUE TITLE
Re-making a new card game off of fork

### ISSUE THREAD

**Issue by asamwow** [Austin-Scott/48HGJSpring2018#41]
Yo Austin,

Here is my new card game I'm working on borrowing a little bit of the implementation from our game jam.

It is private, but since you are a contributor, I think you have access.

https://github.com/asamwow/HandOfLife

I just started yesterday, so not much to look at yet, but you could look at the readme. I only cleaned a lot of stuff up and started to make the card class better (cleaner animated movement implementation).

If you have access, feel free to contribute in the future if you want. I will try to keep it well documented.

-Sam

**Comment by Austin-Scott** [comment]
Awesome! I don't think I've been added as a contributor because I can't see the project that you linked. I would love to have access to the repository to help when I get time. I won't push any changes I make directly into the repository without opening a pull request for the changes to be reviewed first.
